name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'
          
      - name: Install app dependencies
        run: go mod tidy
        
      - name: Build app
        run: go build -v ./cmd/app/main.go
        
      - name: Build app
        run: go build -v ./cmd/app/main.go

      - name: Lint app
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60

      - name: Set up QEMU for Docker build
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: inspirate789/rsoi-lab1:latest
          build-args: |
            PIPELINE_ID=${{ github.run_id }}
            
      - name: Prepare app config on production VM
        shell: bash
        env:
          PROD_USERNAME: ${{ secrets.PROD_USERNAME }}
          PROD_CONFIG: ${{secrets.PROD_CONFIG}}
        run: >-
          touch /home/$PROD_USERNAME/app.yaml &&
          echo "$PROD_CONFIG" > /home/$PROD_USERNAME/app.yaml

      - name: Deploy to production VM
        uses: appleboy/ssh-action@v1.0.3
        env:
          PROD_PORT: ${{ secrets.PROD_PORT }}
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          passphrase: ${{ secrets.PROD_SSH_PASSPHRASE }}
          allenvs: true
          script: >-
            docker pull inspirate789/rsoi-lab1:latest &&
            (docker stop app && docker rm app || true) &&
            docker run --name app -v ~/app.yaml:/app.yaml -p $PROD_PORT:8080 -d inspirate789/rsoi-lab1:latest

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman/[inst] Lab1.postman_collection.json
          environment: postman/[inst][heroku] Lab1.postman_environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 1
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"
